# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    items_directory: '%kernel.project_dir%/public/uploads/items'
    default_locale: 'en'
    # Dropbox Token for Support Tickets
    kernel.dropbox_app_key: '%env(DROPBOX_APP_KEY)%'
    kernel.dropbox_app_secret: '%env(DROPBOX_APP_SECRET)%'
    kernel.dropbox_refresh_token: '%env(DROPBOX_REFRESH_TOKEN)%'

    # kernel.ms_client_id: '%env(MS_CLIENT_ID)%'
    # kernel.ms_tenant_id: '%env(MS_TENANT_ID)%'
    # kernel.ms_client_secret: '%env(MS_CLIENT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\SalesforceService:
        arguments:
            $clientId: '%env(SALESFORCE_CLIENT_KEY)%'
            $clientSecret: '%env(SALESFORCE_CLIENT_SECRET)%'
            $username: '%env(SALESFORCE_USERNAME)%'
            $password: '%env(SALESFORCE_PASSWORD)%'
            $loginUrl: '%env(SALESFORCE_LOGIN_URL)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
